sudo: false
dist: trusty
language: java
# jdk: oraclejdk9 -- install and use jdk-10-ea

install:
- . ./install-jdk.sh

script:
- ./build.jsh

after_success:
- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
- ./bootstrap.jsh

- cd $TRAVIS_BUILD_DIR/demo/01-hello-world
- ./build-01-hello-world.jsh

- cd $TRAVIS_BUILD_DIR/demo/02-testing
- ./build-demo-02-testing.jsh
