sudo: false
dist: trusty
language: java

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

matrix:
  include:
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
  allow_failures:
    # JaCoCo is not yet working on JDK 11
    - env: JDK='Oracle JDK 11'
    - env: JDK='OpenJDK 11'

script:
- java --version
- ./build.jsh

after_success:
- bash <(curl -s https://codecov.io/bash)

- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
- ./bootstrap.jsh

- cd $TRAVIS_BUILD_DIR/demo/01-hello-world
- ./build-01-hello-world.jsh
