sudo: false
dist: trusty
language: java
jdk: oraclejdk9

script:
- ./build.jsh

after_success:
- cd demo/00-bootstrap
- ./bootstrap.jsh
- cd -

- cd demo/01-hello-world
- ./build-01-hello-world.jsh
- cd -
