sudo: false
dist: trusty
language: java

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

matrix:
  include:
    - env: JDK_RELEASE='JDK 8 (Travis CI)'
      jdk: oraclejdk8
    - env: JDK_RELEASE='JDK 9 (Travis CI)'
      jdk: oraclejdk9
    - env: JDK_RELEASE='OpenJDK 9'
      install: . ./install-jdk.sh -F 9
    - env: JDK_RELEASE='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
    - env: JDK_RELEASE='OracleJDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL

script:
- java --version
