sudo: false
dist: trusty
language: java

matrix:
  include:
# OpenJDK 10
    - env: JDK_RELEASE='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
# OracleJDK 10
    - env: JDK_RELEASE='OracleJDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL

script:
- ./build.jsh

after_success:
- cd $TRAVIS_BUILD_DIR/demo/00-bootstrap
- ./bootstrap.jsh

- cd $TRAVIS_BUILD_DIR/demo/01-hello-world
- ./build-01-hello-world.jsh

- cd $TRAVIS_BUILD_DIR/demo/02-testing
- ./build-demo-02-testing.jsh
