sudo: false
dist: trusty
language: java

install:
- cd ~
- wget http://download.java.net/java/jdk9/archive/170/binaries/jdk-9-ea+170_linux-x64_bin.tar.gz
- tar -xzf jdk-9-ea+170_linux-x64_bin.tar.gz
- JAVA_HOME=~/jdk-9
- PATH=$JAVA_HOME/bin:$PATH
- java -version

script:
- cd $TRAVIS_BUILD_DIR
- chmod u+x build.jsh demo.jsh
- ./build.jsh
- ./demo.jsh
