sudo: false
dist: trusty
language: java

install:
- cd ~
- wget http://download.java.net/java/jdk9/archive/173/binaries/jdk-9-ea+173_linux-x64_bin.tar.gz
- tar -xzf jdk-9-ea+173_linux-x64_bin.tar.gz
- JAVA_HOME=~/jdk-9
- PATH=$JAVA_HOME/bin:$PATH
- cd $TRAVIS_BUILD_DIR

script:
- java -version
#- ./build.jsh
#- ./test.jsh
#- ./demo.jsh
